add mini-piggyback migrator for removing `pin_compatible("numpy"...)`
regro/cf-scripts pull request #2470
Opened 2024-04-20 10:19 UTC by h-vetinari

Fixes #2469; goes hand-in-hand with (the migrator filename used in) https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/5790

This is a baby version of #2135 / #1668, where we've already extensively tested the used functionality. Strictly speaking, we could even avoid the whole dance with `_slice_into_output_sections` and just directly remove any lines matching the regex pattern for `pin_compatible("numpy",...)` in the meta.yaml. However, I left it in for now in case anyone wants to add some logic that takes into account existing host-/run-dependencies, because then we need to operate on a per-section basis.

2024-04-20 10:54 UTC, beckermr requested changes
The `_slice_into_output_sections` can raise an error. This made sense for the stdlib work, but here we could iterate through the lines and do a straight replacement. 

Also, the code will fail if people do unusual but valid things in yaml like an explicit list. I don't think we should handle this last case maybe?

2024-04-20 11:06 UTC, h-vetinari commented
> Also, the code will fail if people do unusual but valid things in yaml like an explicit list. I don't think we should handle this last case maybe?

You mean like:
```
run: [{{ pin_compatible("numpy") }}, something_else]
```
?

> The `_slice_into_output_sections` can raise an error. This made sense for the stdlib work, but here we could iterate through the lines and do a straight replacement.

Fine by me.

2024-04-20 11:14 UTC, beckermr commented
Yes I mean like this `run: [{{ pin_compatible("numpy") }}, something_else]`.

2024-04-20 11:15 UTC, beckermr commented on conda_forge_tick/migrators/numpy2.py
> +                fp.write("".join(new_lines))
This looks wrong?

```suggestion
            # _replacer take the raw pattern, not the compiled one
            lines = _replacer(lines, raw_pat_pcn, "")

            with open(fname, "w") as fp:
                fp.write("".join(lines))
```

2024-04-20 11:15 UTC, h-vetinari commented on conda_forge_tick/migrators/numpy2.py
> +                fp.write("".join(new_lines))
Yeah, getting tired. 😑

2024-04-20 11:16 UTC, h-vetinari commented
> Yes I mean like this `run: [{{ pin_compatible("numpy") }}, something_else]`.

It's already handled. The regular expression doesn't care what comes before the first `{`

2024-04-20 11:17 UTC, beckermr commented
Ah but if _replacer ignores the whole line, then we delete the entire run section?

2024-04-20 11:24 UTC, h-vetinari commented
> Ah but if _replacer ignores the whole line, then we delete the entire run section?

It doesn't ignore it, it deletes it. If that ends up creating an empty run-section that's not worth cleaning up automatically IMO - too many corner cases (comments, etc.). We also didn't do that for boost or stdlib either, e.g. they produced
```diff
     run:
-       - boost-cpp
```
or
```diff
     run_constrained:
-       - __osx >={{ MACOSX_DEPLOYMENT_TARGET|default("10.9") }}  # [osx and x86_64]
```
and that was fine?

2024-04-20 11:55 UTC, beckermr commented
Yep agreed! I was just checking that I understood the code.

2024-04-20 11:55 UTC, beckermr approved these changes

2024-04-20 12:14 UTC, merged

2024-04-22 14:54 UTC, jakirkham commented
Thanks Axel and Matt! 🙏

Have we seen this piggyback migrator applied in any PRs? Would be interesting to see how it is doing

2024-04-22 22:58 UTC, h-vetinari commented
> Have we seen this piggyback migrator applied in any PRs? Would be interesting to see how it is doing

It explicitly looks for the `numpy2.yaml` from https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/5790. As long as that PR is not merged, the piggyback won't ever be applied.

2024-04-23 03:58 UTC, jakirkham commented
Interesting am curious is there a particular reason to wait for NumPy 2 to make this change?

As noted in issue ( https://github.com/regro/cf-scripts/issues/2469 ), this change should be ok to make with the current NumPy pinning

Please let me know if this is more to the story

2024-04-23 04:10 UTC, h-vetinari commented
> is there a particular reason to wait for NumPy 2 to make this change?

You're right that we _could_ already remove it based on the existing 1.x infrastructure, but it's a numpy-related change - IMO it makes sense to roll it out together with the numpy migrator, rather than just attach it to random migrators or version updates.