misc: disable meta.yaml for cross_compile.py
regro/cf-scripts pull request #2918
Opened 2024-08-07 08:19 UTC by nichmor

Description:

Checklist:

- [ ] Pydantic model updated or no update needed

Cross-refs, links to issues, etc:

2024-08-07 09:10 UTC, wolfv commented on conda_forge_tick/utils.py
>  import pprint
this is a leftover?

2024-08-07 09:53 UTC, nichmor commented on conda_forge_tick/utils.py
>  import pprint
yes, thanks

2024-08-07 11:19 UTC, beckermr commented
Can you fill out the PR description to provide the motivation for this one? I can think of easier ways to do this and am curious what the global plan is.

2024-08-07 11:24 UTC, wolfv commented
@beckermr - we wanted to prevent a situation where new feedstocks would somehow trip up migrations. There are a couple places where the `meta.yaml` file is unconditionally loaded. 

Any hints / ideas welcome!

2024-08-07 11:26 UTC, beckermr commented
Thanks @wolfv! That makes sense. Let me think on this a bit.

2024-08-08 14:09 UTC, wolfv commented
@beckermr any new ideas? :) Sorry for the turmoil

2024-08-08 14:22 UTC, beckermr requested changes
No worries on the turmoil! Thanks for the hard work. So I had a few ideas but I ended up hating all of them. Here is what we should do.

1. This PR has missed some of the migrators (the graph / ABI ones). We should fix that unless it was purposeful in which case we should discuss.

2. Let's make a single tracking issue that has a list of the skipped migrators to figure out if we will enable for v2 and if we do, we can link to the PR.

2024-08-08 14:27 UTC, nichmor commented
> No worries on the turmoil! Thanks for the hard work. So I had a few ideas but I ended up hating all of them. Here is what we should do.
> 
> 1. This PR has missed some of the migrators (the graph / ABI ones). We should fix that unless it was purposeful in which case we should discuss.
> 2. Let's make a single tracking issue that has a list of the skipped migrators to figure out if we will enable for v2 and if we do, we can link to the PR.

Hey @beckermr ! sorry if I'm being slow - could you please point me where it is the graph or abi migrator located?

2024-08-08 14:33 UTC, beckermr commented
It is in the file called `core.py` in the same module. There appear to a lot of other migrators we have missed. Are those OK? We need to check all of them.

2024-08-10 06:19 UTC, wolfv commented
@beckermr - I searched but didn't find anything in `core.py`.

2024-09-19 14:47 UTC, beckermr requested changes
So I don't get why this PR doesn't just add statements in the filter functions to bypass v1 recipes.

2024-09-19 16:04 UTC, closed without merging