(Git-3) Use GitCli to Commit Migrations
regro/cf-scripts pull request #2948
Opened 2024-08-23 08:45 UTC by ytausch

#### Description:

This is the next step after #2873 and is intended to be merged after.

#### Checklist:

- [x] Pydantic model updated or no update needed

#### Cross-refs, links to issues, etc:

2024-09-06 14:47 UTC, ytausch commented
@beckermr rebase complete!

2024-09-07 11:12 UTC, ytausch commented
@jaimergp If you want to review, feel free to do so as well!

2024-09-07 11:36 UTC, beckermr requested changes
One typo, but otherwise LGTM!

2024-09-07 11:36 UTC, beckermr commented on conda_forge_tick/auto_tick.py
> +    # feedstock_dir must be absolute
```suggestion
    # feedstock_dir must be absolute path
```

2024-09-07 11:40 UTC, beckermr approved these changes

2024-09-07 11:53 UTC, merged