(Git-5) Refactor
regro/cf-scripts pull request #3003
Opened 2024-09-16 07:51 UTC by ytausch

#### Description:

Building upon #3000, this PR refactors the solvability checking code in auto_tick.

#### Checklist:

- [x] Pydantic model updated or no update needed

#### Cross-refs, links to issues, etc:

#3000 needs to be merged first.

2024-09-17 10:42 UTC, beckermr requested changes
You use `textwrap.dedent` but as far as I can tell, you have removed the import.

2024-09-23 09:08 UTC, ytausch commented
@beckermr I think you were mislead here. I have removed the import `from textwrap import dedent` but there is still a `import textwrap` import which is used. No import errors here.

2024-09-23 10:25 UTC, beckermr commented
Ack I missed that. Thank you and LGTM!

2024-09-23 10:25 UTC, beckermr approved these changes

2024-09-23 10:25 UTC, merged